/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"

numbers *
print_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static numbers  result;
	int a[100];

	printf("begin! \n");
	for (int i=0;i<100;i++)
	{
		printf("%d ->", argp->a[i]);
		result.a[i]=argp->a[i]+100;
	}
	printf(" \n");
	return &result;
}
