#include "quicksort.h"

/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

numbers *
qs5000_prog_1(char *host, numbers *params)
{
	CLIENT *clnt;
	numbers  *result_1;
	numbers* qsort_1_arg = params;

#ifndef	DEBUG
	// setup remote connection
	clnt = clnt_create (host, QS5000_PROG, QS5000_V1, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	// call to remote
	result_1 = qsort_1(qsort_1_arg, clnt);
	if (result_1 == (numbers *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	// get return values from result
	// 
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	return result_1;
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	// process quicksort ----------------------------------------------------------
	srand(time(0));	
	int err = 0;
 	
	time_t s100, e100, s1000, e1000, s5000, e5000;   // start and end times for all runs
 	int pos;	
	int elements = 1000;

	int arr[elements];

	// mark start time
        time(&s100);		

	for (pos = 0; pos <= elements-1; pos++ ) {
	arr[pos] = rand() % 10001;
	}	
	int n = sizeof(arr)/sizeof(arr[0]);
	printf("Original array: \n");
	printArray(arr, n);
	int pivot = partition(arr, 0, n-1);
	int arrHighSize = n - pivot;

	printf("pivotIndex = %d, n = %d arrHighSize = %d \n", pivot, n, arrHighSize);

	// create sub arrays
	extractArrayStruct(&arrayParamsLow, arr, ZERO, pivot);
	extractArrayStruct(&arrayParamsHigh, arr, pivot, arrHighSize);
	printArray(arrayParamsLow.a, pivot);
	printArray(arrayParamsHigh.a, arrHighSize);

        //send upper portion to thread
	if (pthread_create(&(tid[1]), NULL, &quickSortThread,(void *)&arrayParamsHigh))
                  printf("\ncan't create thread :[%s] \n", strerror(err));
 
	//send lower portion to remote
	// call to rpc stub ++++++++++++
	arrayParams = *(qs5000_prog_1 (host, &arrayParamsLow));

	//if (pthread_create(&(tid[0]), NULL, &quickSortThread,(void *)&arrayParamsLow))
        //          printf("\ncan't create thread :[%s] \n", strerror(err));

       
	// process upper portion
	//quickSort(arrHigh, 0, arrHighSize-1);
	//wait for thread to complete
	//pthread_join(tid[0], NULL);
	pthread_join(tid[1], NULL);

	printf("Sorted arrayParamsLow: \n");
	printArray(arrayParams.a, arrayParamsLow.high+1);
	printf("Sorted arrayParamsHigh: \n");
	printArray(arrayParamsHigh.a, arrHighSize);

	// mark end time
	time(&e100);	
	printf("Start time: %s\n", ctime(&s100));
	printf("End time : %s\n", ctime(&e100));
	printf("Runtime in seconds : %f \n", difftime(e100, s100));

exit (0);
}
