#include "quicksort.h"

/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

numbers *
gs100_prog_1(char *host, numbers *params)
{
	CLIENT *clnt;
	numbers  *result_1;
	numbers* qsort_1_arg = params;

#ifndef	DEBUG
	// setup remote connection
	clnt = clnt_create (host, GS100_PROG, GS100_V1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	// call to remote
	result_1 = qsort_1(qsort_1_arg, clnt);
	if (result_1 == (numbers *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	// get return values from result
	// 
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	return result_1;
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	// process quicksort ----------------------------------------------------------
	int err = 0;

	int arr[] = {10, 7, 8, 88, 9, 1, 99, 5, 32, 29, 2, 104, 11};
	int n = sizeof(arr)/sizeof(arr[0]);
	printf("Original array: \n");
	printArray(arr, n);
	int pivot = partition(arr, 0, n-1);
	int arrHighSize = n - pivot;

	printf("pivotIndex = %d, n = %d arrHighSize = %d \n", pivot, n, arrHighSize);

	// create sub arrays
	extractArrayStruct(&arrayParamsLow, arr, ZERO, pivot);
	extractArrayStruct(&arrayParamsHigh, arr, pivot, arrHighSize);
	printArray(arrayParamsLow.a, pivot);
	printArray(arrayParamsHigh.a, arrHighSize);

        //send upper portion to thread
	if (pthread_create(&(tid[1]), NULL, &quickSortThread,(void *)&arrayParamsHigh))
                  printf("\ncan't create thread :[%s] \n", strerror(err));
 
	//send lower portion to remote
	// call to rpc stub ++++++++++++
	arrayParams = *(gs100_prog_1 (host, &arrayParamsLow));

	//if (pthread_create(&(tid[0]), NULL, &quickSortThread,(void *)&arrayParamsLow))
        //          printf("\ncan't create thread :[%s] \n", strerror(err));

       
	// process upper portion
	//quickSort(arrHigh, 0, arrHighSize-1);
	//wait for thread to complete
	//pthread_join(tid[0], NULL);
	pthread_join(tid[1], NULL);

	printf("Sorted arrayParamsLow: \n");
	printArray(arrayParams.a, arrayParamsLow.high+1);
	printf("Sorted arrayParamsHigh: \n");
	printArray(arrayParamsHigh.a, arrHighSize);
	
exit (0);
}
