/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "quicksort.h"

numbers *
qsort_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static numbers  result;
	int *arr = argp->a;
	int low =  argp->low;
	int high = argp->high;
	
	printf("Start qsort_1_svc \n");
	printf("argp.a[0]= %d, arr[0]= %d \n", argp->a[0], arr[0]);
	// insert server code here
	quickSort(arr, low, high);
	
	result = *argp;
	printf("After sort \n");
	printf("argp.a[0]= %d, arr[0]= %d result.a[0]= %d \n", argp->a[0], arr[0], result.a[0]);

	return &result;
}
